import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Header
    'header.logo': 'Shelfie',
    'header.joinWaitlist': 'Join Waitlist',
    'header.join': 'Join',
    
    // Hero
    'hero.welcome': 'Welcome to',
    'hero.subtitle': 'Curate and Build Your Digital Shelf of Favorites',
    'hero.joinWaitlist': 'Join the Waitlist',
    
    // How It Works
    'howItWorks.step1.title': 'Add Your Favorites',
    'howItWorks.step1.description': 'Start by adding books, movies, music, and TV shows you love to your digital shelf.',
    'howItWorks.step2.title': 'Connect with Friends',
    'howItWorks.step2.description': 'Share your shelf with friends and discover their favorite content through social connections.',
    'howItWorks.step3.title': 'Discover & Organize',
    'howItWorks.step3.description': 'Get personalized recommendations and organize your collection with smart categorization.',
    
    // Features
    'features.title': 'Everything You Love,',
    'features.organized': 'Organized',
    'features.subtitle': 'Build your digital shelf and share your passions with the world',
    
    // Footer
    'footer.description': 'Build your digital shelf of favorites. Organize, share, and discover books, movies, music, and TV shows with friends.',
    'footer.contact': 'Contact',
    'footer.contactDescription': 'Get in touch with us:',
    'footer.copyright': 'All rights reserved.',
    'footer.helpCenter': 'Help Center',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    
    // Waitlist Modal
    'waitlist.title': 'Join the Waitlist',
    'waitlist.description': 'Be the first to know when Shelfie launches and get early access to organize your digital shelf!',
    'waitlist.name': 'Name',
    'waitlist.email': 'Email',
    'waitlist.namePlaceholder': 'Your name',
    'waitlist.emailPlaceholder': 'your@email.com',
    'waitlist.submit': 'Join Waitlist',
    'waitlist.submitting': 'Joining...',
    'waitlist.success': 'Welcome to the waitlist! 🎉',
    'waitlist.successDescription': "We'll notify you when Shelfie launches.",
    'waitlist.error': 'Missing information',
    'waitlist.errorDescription': 'Please fill in both your name and email.',
    
    // Error Messages
    'error.title': 'Error',
    'error.description': 'Something went wrong. Please try again.',
    
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.back': 'Back',
    'privacy.lastUpdated': 'Last Updated: December 29, 2024',
    'privacy.intro': 'This Privacy Policy describes how Shelfie ("we," "our," or "us") collects, uses, and shares your personal information when you use our mobile application and website (collectively, the "Service"). By using the Service, you agree to the collection and use of information in accordance with this policy.',
    'privacy.section1.title': '1. Information We Collect',
    'privacy.section1.intro': 'We collect information you provide directly to us, such as when you create an account, use our Service, or contact us for support.',
    'privacy.section1.accountInfoTitle': 'Account Information:',
    'privacy.section1.accountInfo1': 'Name, email address, username, and password',
    'privacy.section1.accountInfo2': 'Profile picture and bio information',
    'privacy.section1.accountInfo3': 'Date of birth and location information',
    'privacy.section1.accountInfo4': 'Phone number (if provided for two-factor authentication)',
    'privacy.section1.contentInfoTitle': 'Content Information:',
    'privacy.section1.contentInfo1': 'Favorite books, movies, TV shows, music, and podcasts',
    'privacy.section1.contentInfo2': 'Posts, comments, and reviews you create',
    'privacy.section1.contentInfo3': 'Messages and communications with other users',
    'privacy.section1.contentInfo4': 'Photos, videos, and other media you share',
    'privacy.section1.usageInfoTitle': 'Usage Information:',
    'privacy.section1.usageInfo1': 'How you interact with our Service',
    'privacy.section1.usageInfo2': 'Pages visited, features used, and time spent',
    'privacy.section1.usageInfo3': 'Device information and IP address',
    'privacy.section1.usageInfo4': 'Location data (if you enable location services)',
    'privacy.section2.title': '2. How We Use Your Information',
    'privacy.section2.intro': 'We use the information we collect to provide, maintain, and improve our Service:',
    'privacy.section2.use1': 'Provide and maintain the Service',
    'privacy.section2.use2': 'Create and manage your account',
    'privacy.section2.use3': 'Process transactions and send related information',
    'privacy.section2.use4': 'Send technical notices, updates, and support messages',
    'privacy.section2.use5': 'Respond to your comments and questions',
    'privacy.section2.use6': 'Provide personalized content and recommendations',
    'privacy.section2.use7': 'Monitor and analyze trends and usage',
    'privacy.section2.use8': 'Detect, prevent, and address technical issues',
    'privacy.section2.use9': 'Ensure security and prevent fraud',
    'privacy.section3.title': '3. How We Share Your Information',
    'privacy.section3.intro': 'We may share your information in the following circumstances:',
    'privacy.section3.consentTitle': 'With Your Consent:',
    'privacy.section3.consent1': 'When you explicitly consent to sharing',
    'privacy.section3.consent2': 'When you choose to make content public',
    'privacy.section3.otherUsersTitle': 'With Other Users:',
    'privacy.section3.otherUsers1': 'Public profile information and posts',
    'privacy.section3.otherUsers2': 'Messages sent to other users',
    'privacy.section3.otherUsers3': 'Comments and interactions on public content',
    'privacy.section3.serviceProvidersTitle': 'With Service Providers:',
    'privacy.section3.serviceProviders1': 'Cloud storage and hosting services',
    'privacy.section3.serviceProviders2': 'Analytics and performance monitoring',
    'privacy.section3.serviceProviders3': 'Customer support and communication tools',
    'privacy.section3.serviceProviders4': 'Payment processing (if applicable)',
    'privacy.section3.legalTitle': 'Legal Requirements:',
    'privacy.section3.legal1': 'To comply with legal obligations',
    'privacy.section3.legal2': 'To protect our rights and property',
    'privacy.section3.legal3': 'To prevent fraud or abuse',
    'privacy.section3.legal4': 'In case of emergency or safety concerns',
    'privacy.section4.title': '4. Data Security',
    'privacy.section4.intro': 'We implement appropriate technical and organizational measures to protect your personal information:',
    'privacy.section4.security1': 'Encryption of data in transit and at rest',
    'privacy.section4.security2': 'Regular security assessments and updates',
    'privacy.section4.security3': 'Access controls and authentication',
    'privacy.section4.security4': 'Secure data centers and infrastructure',
    'privacy.section4.security5': 'Employee training on data protection',
    'privacy.section4.warning': 'However, no method of transmission over the internet or electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee absolute security.',
    'privacy.section5.title': '5. Your Rights and Choices',
    'privacy.section5.intro': 'You have certain rights regarding your personal information:',
    'privacy.section5.rights1': 'Access: Request a copy of your personal information',
    'privacy.section5.rights2': 'Correction: Update or correct inaccurate information',
    'privacy.section5.rights3': 'Deletion: Request deletion of your personal information',
    'privacy.section5.rights4': 'Portability: Export your data in a machine-readable format',
    'privacy.section5.rights5': 'Restriction: Limit how we process your information',
    'privacy.section5.rights6': 'Objection: Object to certain processing activities',
    'privacy.section5.requestData': 'Request Your Data',
    'privacy.section6.title': '6. Data Retention',
    'privacy.section6.content': 'We retain your personal information for as long as necessary to provide our Service and fulfill the purposes outlined in this Privacy Policy. We will delete or anonymize your information when it is no longer needed, unless we are required to retain it for legal or regulatory purposes.',
    'privacy.section7.title': '7. Children\'s Privacy',
    'privacy.section7.content': 'Our Service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us so we can delete such information.',
    'privacy.section8.title': '8. International Data Transfers',
    'privacy.section8.content': 'Your information may be transferred to and processed in countries other than your own. We ensure that such transfers comply with applicable data protection laws and implement appropriate safeguards to protect your information.',
    'privacy.section9.title': '9. Third-Party Services',
    'privacy.section9.intro': 'Our Service may contain links to third-party websites or services. We are not responsible for the privacy practices of these third parties. We encourage you to read their privacy policies before providing any information.',
    'privacy.section9.integratedServicesTitle': 'Integrated Services:',
    'privacy.section9.integratedServices1': 'Spotify (for music recommendations)',
    'privacy.section9.integratedServices2': 'Goodreads (for book recommendations)',
    'privacy.section9.integratedServices3': 'Letterboxd (for movie recommendations)',
    'privacy.section9.integratedServices4': 'Apple Music (for music integration)',
    'privacy.section10.title': '10. Changes to This Privacy Policy',
    'privacy.section10.content': 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. We encourage you to review this Privacy Policy periodically for any changes.',
    'privacy.section11.title': '11. California Privacy Rights',
    'privacy.section11.intro': 'If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA):',
    'privacy.section11.rights1': 'Right to know what personal information is collected',
    'privacy.section11.rights2': 'Right to delete personal information',
    'privacy.section11.rights3': 'Right to opt-out of the sale of personal information',
    'privacy.section11.rights4': 'Right to non-discrimination for exercising privacy rights',
    'privacy.section12.title': '12. European Privacy Rights',
    'privacy.section12.intro': 'If you are in the European Economic Area (EEA), you have rights under the General Data Protection Regulation (GDPR):',
    'privacy.section12.rights1': 'Right of access to your personal data',
    'privacy.section12.rights2': 'Right to rectification of inaccurate data',
    'privacy.section12.rights3': 'Right to erasure ("right to be forgotten")',
    'privacy.section12.rights4': 'Right to restrict processing',
    'privacy.section12.rights5': 'Right to data portability',
    'privacy.section12.rights6': 'Right to object to processing',
    'privacy.contactUsTitle': 'Contact Us',
    'privacy.contactUsIntro': 'If you have any questions about this Privacy Policy or our privacy practices, please contact us:',
    'privacy.contactUsEmail': 'By email: shelfieplatform@gmail.com',
    'privacy.contactUsWebsite': 'By visiting: https://shelfieplatform.com',
    'privacy.contactPrivacyTeam': 'Contact Privacy Team',
    
    // Help Center
    'helpCenter.title': 'Help Center',
    'helpCenter.back': 'Back',
    'helpCenter.hero.title': 'How can we help you?',
    'helpCenter.hero.subtitle': 'Find answers, get support, and learn how to make the most of Shelfie',
    'helpCenter.search.placeholder': 'Search help articles...',
    'helpCenter.categories.title': 'Browse by Category',
    'helpCenter.categories.viewAll': 'View all articles',
    'helpCenter.categories.gettingStarted.title': 'Getting Started',
    'helpCenter.categories.gettingStarted.description': 'Learn the basics of using Shelfie',
    'helpCenter.categories.accountProfile.title': 'Account & Profile',
    'helpCenter.categories.accountProfile.description': 'Manage your account and profile settings',
    'helpCenter.categories.addingFavorites.title': 'Adding Favorites',
    'helpCenter.categories.addingFavorites.description': 'Add and organize your favorite content',
    'helpCenter.categories.privacySecurity.title': 'Privacy & Security',
    'helpCenter.categories.privacySecurity.description': 'Protect your privacy and secure your account',
    'helpCenter.categories.troubleshooting.title': 'Troubleshooting',
    'helpCenter.categories.troubleshooting.description': 'Fix common issues and problems',
    'helpCenter.categories.contactSupport.title': 'Contact Support',
    'helpCenter.categories.contactSupport.description': 'Get direct help from our support team',
    'helpCenter.popular.title': 'Popular Articles',
    'helpCenter.popular.welcome.title': 'Welcome to Shelfie',
    'helpCenter.popular.welcome.description': 'Your first steps on the platform',
    'helpCenter.popular.setupProfile.title': 'Setting up your profile',
    'helpCenter.popular.setupProfile.description': 'Create an engaging profile that reflects your interests',
    'helpCenter.popular.addBooks.title': 'Adding books to your favorites',
    'helpCenter.popular.addBooks.description': 'Start building your digital shelf with books',
    'helpCenter.popular.privacySettings.title': 'Privacy settings guide',
    'helpCenter.popular.privacySettings.description': 'Control who can see your content and activity',
    'helpCenter.contact.title': 'Still need help?',
    'helpCenter.contact.description': 'Our support team is here to help you with any questions or issues.',
    'helpCenter.contact.emailSupport': 'Email Support',
    'helpCenter.contact.contactForm': 'Contact Form',
    'helpCenter.backToHelpCenter': 'Back to Help Center',
    'helpCenter.gettingStarted.welcome.title': 'Welcome to Shelfie: Your First Steps',
    'helpCenter.gettingStarted.welcome.description': 'Get started with Shelfie and learn the basics of building your digital shelf',
    'helpCenter.gettingStarted.creatingAccount.title': 'Creating Your Account',
    'helpCenter.gettingStarted.creatingAccount.description': 'Learn how to create your Shelfie account and get verified',
    'helpCenter.gettingStarted.settingUpProfile.title': 'Setting Up Your Profile',
    'helpCenter.gettingStarted.settingUpProfile.description': 'Create an engaging profile that reflects your interests and preferences',
    'helpCenter.gettingStarted.dashboard.title': 'Understanding Your Dashboard',
    'helpCenter.gettingStarted.dashboard.description': 'Navigate your dashboard and understand the main features',
    'helpCenter.gettingStarted.privacySettings.title': 'Privacy Settings Overview',
    'helpCenter.gettingStarted.privacySettings.description': 'Control who can see your content and manage your privacy',
    'helpCenter.gettingStarted.mobileApp.title': 'Mobile App Download',
    'helpCenter.gettingStarted.mobileApp.description': 'Download the Shelfie mobile app for iOS and Android',
    'helpCenter.gettingStarted.desktopMobile.title': 'Desktop vs Mobile Experience',
    'helpCenter.gettingStarted.desktopMobile.description': 'Understand the differences between web and mobile platforms',
    'helpCenter.gettingStarted.firstFollowers.title': 'Getting Your First Followers',
    'helpCenter.gettingStarted.firstFollowers.description': 'Tips for building your community and gaining followers',
    'helpCenter.gettingStarted.followingUsers.title': 'Following Other Users',
    'helpCenter.gettingStarted.followingUsers.description': 'Discover and follow users with similar interests',
    'helpCenter.gettingStarted.notifications.title': 'Understanding Notifications',
    'helpCenter.gettingStarted.notifications.description': 'Manage your notification preferences and stay updated',
    'helpCenter.gettingStarted.securityTips.title': 'Basic Security Tips',
    'helpCenter.gettingStarted.securityTips.description': 'Essential security practices to protect your account',
    'helpCenter.gettingStarted.platformTour.title': 'Platform Tour',
    'helpCenter.gettingStarted.platformTour.description': 'Take a guided tour of all Shelfie features and capabilities',
    'helpCenter.backToCategory': 'Back to Category',
    'helpCenter.articles.welcome.title': 'Welcome to Shelfie: Your First Steps',
    'helpCenter.articles.welcome.subtitle': 'Get started with Shelfie and learn the basics of building your digital shelf',
    'helpCenter.articles.welcome.readTime': '5 min read',
    'helpCenter.articles.welcome.lastUpdated': 'Last updated: December 2024',
    'helpCenter.articles.welcome.introduction.title': 'Welcome to Your Digital Shelf',
    'helpCenter.articles.welcome.introduction.content': 'Shelfie is a social media platform designed specifically for sharing and discovering your favorite books, movies, music, and TV shows. Unlike traditional social media focused on personal updates, Shelfie is centered around content discovery and building your "digital shelf" of favorites.',
    'helpCenter.articles.welcome.introduction.highlight': 'What makes Shelfie different?',
    'helpCenter.articles.welcome.introduction.highlightContent': 'Shelfie focuses on content curation rather than personal updates, helping you discover new books, movies, and music through your social network.',
    'helpCenter.articles.welcome.features.title': 'Key Features',
    'helpCenter.articles.welcome.features.digitalShelf.title': 'Digital Shelf',
    'helpCenter.articles.welcome.features.digitalShelf.description': 'Build and organize your collection of favorite books, movies, music, and TV shows in one place.',
    'helpCenter.articles.welcome.features.socialDiscovery.title': 'Social Discovery',
    'helpCenter.articles.welcome.features.socialDiscovery.description': 'Follow other users to discover new content and share your favorites with your community.',
    'helpCenter.articles.welcome.features.community.title': 'Community',
    'helpCenter.articles.welcome.features.community.description': 'Connect with like-minded users who share your interests in books, movies, and music.',
    'helpCenter.articles.welcome.features.recommendations.title': 'Smart Recommendations',
    'helpCenter.articles.welcome.features.recommendations.description': 'Get personalized content suggestions based on your preferences and social connections.',
    'helpCenter.articles.welcome.steps.title': 'Getting Started Checklist',
    'helpCenter.articles.welcome.steps.createAccount': 'Create your account and choose a username',
    'helpCenter.articles.welcome.steps.setupProfile': 'Set up your profile with bio and interests',
    'helpCenter.articles.welcome.steps.addFavorites': 'Start adding your favorite books, movies, and music',
    'helpCenter.articles.welcome.steps.followUsers': 'Follow other users with similar interests',
    'helpCenter.articles.welcome.steps.exploreContent': 'Explore and discover new content through recommendations',
    'helpCenter.articles.welcome.tips.title': 'Success Tips',
    'helpCenter.articles.welcome.tips.tip1.title': 'Complete Your Profile',
    'helpCenter.articles.welcome.tips.tip1.content': 'A complete profile with bio and interests helps others discover you and improves your content recommendations.',
    'helpCenter.articles.welcome.tips.tip2.title': 'Be Active in the Community',
    'helpCenter.articles.welcome.tips.tip2.content': 'Like, comment, and share content from other users to build connections and discover new favorites.',
    'helpCenter.articles.welcome.tips.tip3.title': 'Use Lists and Collections',
    'helpCenter.articles.welcome.tips.tip3.content': 'Organize your favorites into themed lists (e.g., "Summer Reads", "Horror Movies") to share with others.',
    'helpCenter.articles.welcome.related.title': 'Related Articles',
    'helpCenter.articles.welcome.related.creatingAccount': 'Creating Your Account',
    'helpCenter.articles.welcome.related.settingUpProfile': 'Setting Up Your Profile',
    'helpCenter.articles.welcome.related.addingBooks': 'Adding Books to Your Favorites',
    'helpCenter.articles.welcome.nextArticle': 'Next: Creating Your Account',
    
    // Account & Profile Category
    'helpCenter.accountProfile.changeUsername.title': 'How to Change Your Username',
    'helpCenter.accountProfile.changeUsername.description': 'Learn how to update your username and what to consider',
    'helpCenter.accountProfile.updateProfile.title': 'Updating Your Profile Information',
    'helpCenter.accountProfile.updateProfile.description': 'Keep your profile information current and accurate',
    'helpCenter.accountProfile.profilePictures.title': 'Adding Profile Pictures',
    'helpCenter.accountProfile.profilePictures.description': 'Upload and manage your profile picture',
    'helpCenter.accountProfile.settingBio.title': 'Setting Your Bio',
    'helpCenter.accountProfile.settingBio.description': 'Write an engaging bio that represents you',
    'helpCenter.accountProfile.connectedAccounts.title': 'Managing Connected Accounts',
    'helpCenter.accountProfile.connectedAccounts.description': 'Link and manage your social media accounts',
    'helpCenter.accountProfile.securitySettings.title': 'Account Security Settings',
    'helpCenter.accountProfile.securitySettings.description': 'Configure your account security preferences',
    'helpCenter.accountProfile.twoFactorAuth.title': 'Two-Factor Authentication Setup',
    'helpCenter.accountProfile.twoFactorAuth.description': 'Enable 2FA for enhanced account security',
    'helpCenter.accountProfile.passwordManagement.title': 'Password Management',
    'helpCenter.accountProfile.passwordManagement.description': 'Change and secure your account password',
    'helpCenter.accountProfile.accountDeactivation.title': 'Account Deactivation',
    'helpCenter.accountProfile.accountDeactivation.description': 'Temporarily or permanently deactivate your account',
    'helpCenter.accountProfile.dataExport.title': 'Data Export',
    'helpCenter.accountProfile.dataExport.description': 'Download your account data and content',
    'helpCenter.accountProfile.accountRecovery.title': 'Account Recovery',
    'helpCenter.accountProfile.accountRecovery.description': 'Recover access to your account if locked out',
    'helpCenter.accountProfile.profileVisibility.title': 'Profile Visibility Settings',
    'helpCenter.accountProfile.profileVisibility.description': 'Control who can see your profile and content',
    
    // Adding Favorites Category
    'helpCenter.addingFavorites.addBooks.title': 'How to Add Books to Your Favorites',
    'helpCenter.addingFavorites.addBooks.description': 'Add books to your digital shelf using search, ISBN, or manual entry',
    'helpCenter.addingFavorites.addMoviesTv.title': 'Adding Movies and TV Shows',
    'helpCenter.addingFavorites.addMoviesTv.description': 'Discover and add movies and TV shows to your collection',
    'helpCenter.addingFavorites.addMusic.title': 'Adding Music and Songs',
    'helpCenter.addingFavorites.addMusic.description': 'Add your favorite music and songs to your shelf',
    'helpCenter.addingFavorites.importLists.title': 'Importing Your Existing Lists',
    'helpCenter.addingFavorites.importLists.description': 'Import your collections from other platforms',
    'helpCenter.addingFavorites.organizeFavorites.title': 'Organizing Your Favorites',
    'helpCenter.addingFavorites.organizeFavorites.description': 'Keep your digital shelf organized and accessible',
    'helpCenter.addingFavorites.customLists.title': 'Creating Custom Lists',
    'helpCenter.addingFavorites.customLists.description': 'Create themed collections like "Summer Reads" or "Horror Movies"',
    'helpCenter.addingFavorites.shareFavorites.title': 'Sharing Your Favorites',
    'helpCenter.addingFavorites.shareFavorites.description': 'Share your favorite content with friends and followers',
    'helpCenter.addingFavorites.findContent.title': 'Finding New Content',
    'helpCenter.addingFavorites.findContent.description': 'Discover new books, movies, and music through recommendations',
    'helpCenter.addingFavorites.ratingReviewing.title': 'Rating and Reviewing',
    'helpCenter.addingFavorites.ratingReviewing.description': 'Rate and write reviews for your favorite content',
    'helpCenter.addingFavorites.manageCollections.title': 'Managing Your Collections',
    'helpCenter.addingFavorites.manageCollections.description': 'Organize and manage your content collections',
    'helpCenter.addingFavorites.bulkImport.title': 'Bulk Import Options',
    'helpCenter.addingFavorites.bulkImport.description': 'Import large lists of content at once',
    'helpCenter.addingFavorites.favoriteCategories.title': 'Favorite Categories',
    'helpCenter.addingFavorites.favoriteCategories.description': 'Organize your favorites by categories and genres',
    
    // Privacy & Security Category
    'helpCenter.privacySecurity.privacySettings.title': 'Understanding Your Privacy Settings',
    'helpCenter.privacySecurity.privacySettings.description': 'Control who can see your profile and content',
    'helpCenter.privacySecurity.profileVisibility.title': 'Who Can See Your Profile',
    'helpCenter.privacySecurity.profileVisibility.description': 'Manage your profile visibility and privacy',
    'helpCenter.privacySecurity.blockingReporting.title': 'Blocking and Reporting Users',
    'helpCenter.privacySecurity.blockingReporting.description': 'Block users and report inappropriate content',
    'helpCenter.privacySecurity.dataProtection.title': 'Data Protection and GDPR',
    'helpCenter.privacySecurity.dataProtection.description': 'Learn about data protection and your rights',
    'helpCenter.privacySecurity.securityBestPractices.title': 'Account Security Best Practices',
    'helpCenter.privacySecurity.securityBestPractices.description': 'Essential security practices to protect your account',
    'helpCenter.privacySecurity.twoFactorAuth.title': 'Two-Factor Authentication',
    'helpCenter.privacySecurity.twoFactorAuth.description': 'Set up 2FA for enhanced account security',
    'helpCenter.privacySecurity.privacyPolicy.title': 'Privacy Policy Overview',
    'helpCenter.privacySecurity.privacyPolicy.description': 'Understand how we protect your privacy',
    'helpCenter.privacySecurity.dataSharing.title': 'Data Sharing Settings',
    'helpCenter.privacySecurity.dataSharing.description': 'Control how your data is shared and used',
    'helpCenter.privacySecurity.thirdPartyIntegrations.title': 'Third-Party Integrations',
    'helpCenter.privacySecurity.thirdPartyIntegrations.description': 'Manage connections to external services',
    'helpCenter.privacySecurity.securityNotifications.title': 'Security Notifications',
    'helpCenter.privacySecurity.securityNotifications.description': 'Stay informed about account security',
    'helpCenter.privacySecurity.accountRecovery.title': 'Account Recovery Options',
    'helpCenter.privacySecurity.accountRecovery.description': 'Recover your account if you lose access',
    'helpCenter.privacySecurity.dataDeletion.title': 'Data Deletion Requests',
    'helpCenter.privacySecurity.dataDeletion.description': 'Request deletion of your personal data',
    
    // Troubleshooting Category
    'helpCenter.troubleshooting.loginIssues.title': 'Login Issues',
    'helpCenter.troubleshooting.loginIssues.description': 'Resolve common login problems and account access issues',
    'helpCenter.troubleshooting.appNotLoading.title': 'App Not Loading',
    'helpCenter.troubleshooting.appNotLoading.description': 'Fix app loading and performance issues',
    'helpCenter.troubleshooting.uploadProblems.title': 'Upload Problems',
    'helpCenter.troubleshooting.uploadProblems.description': 'Resolve issues with uploading content and media',
    'helpCenter.troubleshooting.searchNotWorking.title': 'Search Not Working',
    'helpCenter.troubleshooting.searchNotWorking.description': 'Fix search functionality and content discovery',
    'helpCenter.troubleshooting.notificationIssues.title': 'Notification Issues',
    'helpCenter.troubleshooting.notificationIssues.description': 'Resolve notification and alert problems',
    'helpCenter.troubleshooting.performanceProblems.title': 'Performance Problems',
    'helpCenter.troubleshooting.performanceProblems.description': 'Improve app and website performance',
    'helpCenter.troubleshooting.browserCompatibility.title': 'Browser Compatibility',
    'helpCenter.troubleshooting.browserCompatibility.description': 'Ensure compatibility with your web browser',
    'helpCenter.troubleshooting.mobileAppIssues.title': 'Mobile App Issues',
    'helpCenter.troubleshooting.mobileAppIssues.description': 'Fix problems with the mobile app',
    'helpCenter.troubleshooting.accountAccess.title': 'Account Access Problems',
    'helpCenter.troubleshooting.accountAccess.description': 'Resolve account access and authentication issues',
    'helpCenter.troubleshooting.dataSync.title': 'Data Sync Issues',
    'helpCenter.troubleshooting.dataSync.description': 'Fix data synchronization between devices',
    'helpCenter.troubleshooting.errorMessages.title': 'Error Messages',
    'helpCenter.troubleshooting.errorMessages.description': 'Understand and resolve common error messages',
    'helpCenter.troubleshooting.contactSupport.title': 'Contact Technical Support',
    'helpCenter.troubleshooting.contactSupport.description': 'Get direct help from our technical support team',
    
    // Contact Support
    'helpCenter.contact.contactOptions.title': 'Contact Options',
    'helpCenter.contact.emailSupport.title': 'Email Support',
    'helpCenter.contact.emailSupport.description': 'Send us an email and we\'ll get back to you',
    'helpCenter.contact.emailSupport.button': 'Send Email',
    'helpCenter.contact.liveChat.title': 'Live Chat',
    'helpCenter.contact.liveChat.description': 'Chat with our support team in real-time',
    'helpCenter.contact.liveChat.button': 'Start Chat',
    'helpCenter.contact.phoneSupport.title': 'Phone Support',
    'helpCenter.contact.phoneSupport.description': 'Call us for immediate assistance',
    'helpCenter.contact.phoneSupport.button': 'Call Now',
    'helpCenter.contact.contactForm.title': 'Contact Form',
    'helpCenter.contact.form.name': 'Name',
    'helpCenter.contact.form.namePlaceholder': 'Your full name',
    'helpCenter.contact.form.email': 'Email',
    'helpCenter.contact.form.emailPlaceholder': 'your@email.com',
    'helpCenter.contact.form.subject': 'Subject',
    'helpCenter.contact.form.subjectPlaceholder': 'Brief description of your issue',
    'helpCenter.contact.form.message': 'Message',
    'helpCenter.contact.form.messagePlaceholder': 'Please describe your issue in detail...',
    'helpCenter.contact.form.submit': 'Send Message',
    'helpCenter.contact.supportInfo.title': 'Support Information',
    'helpCenter.contact.supportHours.title': 'Support Hours',
    'helpCenter.contact.supportHours.content': 'Monday - Friday: 9 AM - 6 PM EST',
    'helpCenter.contact.responseTimes.title': 'Response Times',
    'helpCenter.contact.responseTimes.content': 'Email: 24-48 hours, Live Chat: Immediate',
    'helpCenter.contact.escalationProcess.title': 'Escalation Process',
    'helpCenter.contact.escalationProcess.content': 'Complex issues escalated to senior support',
    'helpCenter.contact.feedbackOptions.title': 'Feedback & Community',
    'helpCenter.contact.feedback.title': 'General Feedback',
    'helpCenter.contact.feedback.description': 'Share your thoughts and suggestions',
    'helpCenter.contact.bugReports.title': 'Bug Reports',
    'helpCenter.contact.bugReports.description': 'Report bugs and technical issues',
    'helpCenter.contact.featureRequests.title': 'Feature Requests',
    'helpCenter.contact.featureRequests.description': 'Suggest new features and improvements',
    'helpCenter.contact.communityForums.title': 'Community Forums',
    'helpCenter.contact.communityForums.description': 'Connect with other Shelfie users',
    
    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.back': 'Back',
    'terms.welcome': 'Welcome to',
    'terms.intro': 'These Terms of Service ("Terms") govern your use of the Shelfie mobile application and related services (collectively, the "Service") operated by Shelfie Inc. ("we," "our," or "us").',
    'terms.lastUpdated': 'Last updated:',
    'terms.contact': 'Contact Information',
    'terms.contactDescription': 'If you have any questions about these Terms of Service, please contact us:',
    'terms.contactSupport': 'Contact Support',
    'terms.viewPrivacyPolicy': 'View Privacy Policy →',
    'terms.section1.title': '1. Acceptance of Terms',
    'terms.section1.content1': 'By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of these terms, then you may not access the Service.',
    'terms.section1.content2': 'We reserve the right to update and change these Terms from time to time without notice. Any new features that augment or enhance the current Service shall be subject to these Terms.',
    'terms.section2.title': '2. Description of Service',
    'terms.section2.content1': 'Shelfie is a social media platform that allows users to share and discover their favorite books, movies, TV shows, music, and podcasts. Our Service includes:',
    'terms.section2.list1': 'Creating and managing personal profiles',
    'terms.section2.list2': 'Sharing favorite content with the community',
    'terms.section2.list3': 'Discovering new content through recommendations',
    'terms.section2.list4': 'Following other users and building connections',
    'terms.section2.list5': 'Accessing personalized content feeds',
    'terms.section2.list6': 'Participating in community discussions',
    'terms.section3.title': '3. User Accounts',
    'terms.section3.content1': 'To access certain features of the Service, you must register for an account. You agree to:',
    'terms.section3.list1': 'Provide accurate, current, and complete information',
    'terms.section3.list2': 'Maintain and update your account information',
    'terms.section3.list3': 'Keep your password secure and confidential',
    'terms.section3.list4': 'Accept responsibility for all activities under your account',
    'terms.section3.list5': 'Notify us immediately of any unauthorized use',
    'terms.section3.content2': 'You must be at least 13 years old to create an account. Users under 18 must have parental consent to use the Service.',
    'terms.section4.title': '4. User Content and Conduct',
    'terms.section4.content1': 'You are responsible for all content you post, upload, or share on the Service. You agree not to:',
    'terms.section4.list1': 'Post content that is illegal, harmful, or violates others\' rights',
    'terms.section4.list2': 'Share copyrighted material without permission',
    'terms.section4.list3': 'Post spam, misleading, or deceptive content',
    'terms.section4.list4': 'Harass, abuse, or harm other users',
    'terms.section4.list5': 'Impersonate others or create fake accounts',
    'terms.section4.list6': 'Use the Service for commercial purposes without permission',
    'terms.section4.content2': 'We reserve the right to remove content that violates these Terms and to suspend or terminate accounts that engage in prohibited activities.',
    'terms.section5.title': '5. Privacy and Data Protection',
    'terms.section5.content1': 'Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service. By using our Service, you agree to the collection and use of information in accordance with our Privacy Policy.',
    'terms.section6.title': '6. Intellectual Property',
    'terms.section6.content1': 'The Service and its original content, features, and functionality are owned by Shelfie Inc. and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.',
    'terms.section6.content2': 'You retain ownership of content you create and share, but grant us a license to use, display, and distribute your content in connection with the Service.',
    'terms.section7.title': '7. Prohibited Uses',
    'terms.section7.content1': 'You may not use our Service:',
    'terms.section7.list1': 'For any unlawful purpose or to solicit others to perform unlawful acts',
    'terms.section7.list2': 'To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances',
    'terms.section7.list3': 'To infringe upon or violate our intellectual property rights or the intellectual property rights of others',
    'terms.section7.list4': 'To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate',
    'terms.section7.list5': 'To submit false or misleading information',
    'terms.section7.list6': 'To upload or transmit viruses or any other type of malicious code',
    'terms.section8.title': '8. Service Availability',
    'terms.section8.content1': 'We strive to provide continuous service availability, but we do not guarantee that the Service will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Service.',
    'terms.section8.content2': 'We reserve the right to change, suspend, or discontinue the Service or any part of it at any time with or without notice.',
    'terms.section9.title': '9. Disclaimers and Limitations',
    'terms.section9.content1': 'The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, expressed or implied, and hereby disclaim all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property.',
    'terms.section9.content2': 'In no event shall Shelfie Inc. be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.',
    'terms.section10.title': '10. Termination',
    'terms.section10.content1': 'We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.',
    'terms.section10.content2': 'If you wish to terminate your account, you may simply discontinue using the Service or contact us to request account deletion.',
    'terms.section11.title': '11. Governing Law',
    'terms.section11.content': 'These Terms shall be interpreted and governed by the laws of the State of California, United States, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.',
    'terms.section12.title': '12. Changes to Terms',
    'terms.section12.content1': 'We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days notice prior to any new terms taking effect.',
    'terms.section12.content2': 'By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.',
    'terms.loading': 'Loading terms of service...',
  },
  tr: {
    // Header
    'header.logo': 'Shelfie',
    'header.joinWaitlist': 'Bekleme Listesine Katıl',
    'header.join': 'Katıl',
    
    // Hero
    'hero.welcome': 'Hoş geldin',
    'hero.subtitle': 'Favorilerini ekle ve kendi dijital rafını oluştur',
    'hero.joinWaitlist': 'Bekleme Listesine Katıl',
    
    // How It Works
    'howItWorks.step1.title': 'Favorilerini Ekle',
    'howItWorks.step1.description': 'Sevdiğin kitapları, filmleri, müzikleri, dizileri ve podcastleri dijital favori rafına ekleyerek başla.',
    'howItWorks.step2.title': 'Arkadaşlarınla Takipleş',
    'howItWorks.step2.description': 'Favorilerini arkadaşlarınla paylaş ve onların favorilerini keşfet.',
    'howItWorks.step3.title': 'Keşfet ve Düzenle',
    'howItWorks.step3.description': 'Sana özel öneriler al, favori koleksiyonunu düzenle.',
    
    // Features
    'features.title': 'Sevdiğin Her Şey,',
    'features.organized': 'Tek Yerde',
    'features.subtitle': 'Favorilerin ile dijital rafını oluştur, tutkularını dünyayla paylaş.',
    
    // Footer
    'footer.description': 'Favorilerinden dijital rafını oluştur. Kitapları, filmleri, müzikleri ve dizileri arkadaşlarınla paylaş ve keşfet.',
    'footer.contact': 'İletişim',
    'footer.contactDescription': 'İletişim:',
    'footer.copyright': 'Tüm hakları saklıdır.',
    'footer.helpCenter': 'Destek Merkezi',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.termsOfService': 'Kullanım Şartları',
    
    // Waitlist Modal
    'waitlist.title': 'Bekleme Listesine Katıl',
    'waitlist.description': 'Shelfie yayına girdiğinde ilk sen öğren, favorilerin ile dijital rafını erkenden düzenlemeye başla!',
    'waitlist.name': 'Ad',
    'waitlist.email': 'E-posta',
    'waitlist.namePlaceholder': 'Adınız',
    'waitlist.emailPlaceholder': 'eposta@ornek.com',
    'waitlist.submit': 'Listeye Katıl',
    'waitlist.submitting': 'Katılıyor...',
    'waitlist.success': 'Bekleme listesine hoş geldin! 🎉',
    'waitlist.successDescription': 'Shelfie yayına girdiğinde sana haber vereceğiz.',
    'waitlist.error': 'Eksik bilgi',
    'waitlist.errorDescription': 'Lütfen adını ve e-postanı doldur.',
    
    // Error Messages
    'error.title': 'Hata',
    'error.description': 'Bir şeyler ters gitti. Lütfen tekrar dene.',
    
    // Privacy Policy
    'privacy.title': 'Gizlilik Politikası',
    'privacy.back': 'Geri',
    'privacy.lastUpdated': 'Son Güncelleme: 29 Aralık 2024',
    'privacy.intro': 'Bu Gizlilik Politikası, Shelfie ("biz", "bize", "bizim") olarak mobil uygulamamızı ve web sitemizi (topluca "Hizmet") kullandığınızda kişisel verilerinizi nasıl topladığımızı, kullandığımızı ve paylaştığımızı açıklar. Hizmeti kullanarak, bilgilerin bu politika uyarınca toplanmasını ve kullanılmasını kabul etmiş olursunuz.',
    'privacy.section1.title': '1. Topladığımız Bilgiler',
    'privacy.section1.intro': 'Hizmetimizi kullanırken veya bizimle iletişime geçtiğinizde bize doğrudan sağladığınız bilgileri toplarız.',
    'privacy.section1.accountInfoTitle': 'Hesap Bilgileri:',
    'privacy.section1.accountInfo1': 'Ad, e-posta adresi, kullanıcı adı ve şifre',
    'privacy.section1.accountInfo2': 'Profil fotoğrafı ve biyografi bilgileri',
    'privacy.section1.accountInfo3': 'Doğum tarihi ve konum bilgileri',
    'privacy.section1.accountInfo4': 'Telefon numarası (iki faktörlü doğrulama için verilmişse)',
    'privacy.section1.contentInfoTitle': 'İçerik Bilgileri:',
    'privacy.section1.contentInfo1': 'Favori kitaplar, filmler, diziler, müzikler ve podcastler',
    'privacy.section1.contentInfo2': 'Oluşturduğunuz gönderiler, yorumlar ve incelemeler',
    'privacy.section1.contentInfo3': 'Diğer kullanıcılarla mesajlar ve yazışmalar',
    'privacy.section1.contentInfo4': 'Paylaştığınız fotoğraflar, videolar ve diğer medya',
    'privacy.section1.usageInfoTitle': 'Kullanım Bilgileri:',
    'privacy.section1.usageInfo1': 'Hizmetle etkileşim şekliniz',
    'privacy.section1.usageInfo2': 'Ziyaret edilen sayfalar, kullanılan özellikler, geçirilen süre',
    'privacy.section1.usageInfo3': 'Cihaz bilgileri ve IP adresi',
    'privacy.section1.usageInfo4': 'Konum verileri (konum servislerini etkinleştirdiyseniz)',
    'privacy.section2.title': '2. Bilgilerinizi Nasıl Kullanıyoruz',
    'privacy.section2.intro': 'Topladığımız bilgileri Hizmeti sunmak, sürdürmek ve geliştirmek için kullanırız:',
    'privacy.section2.use1': 'Hizmeti sağlamak ve işletmek',
    'privacy.section2.use2': 'Hesabınızı oluşturmak ve yönetmek',
    'privacy.section2.use3': 'İşlemleri gerçekleştirmek ve ilgili bilgileri göndermek',
    'privacy.section2.use4': 'Teknik bildirimler, güncellemeler ve destek mesajları iletmek',
    'privacy.section2.use5': 'Yorumlarınıza ve sorularınıza yanıt vermek',
    'privacy.section2.use6': 'Kişiselleştirilmiş içerik ve öneriler sunmak',
    'privacy.section2.use7': 'Trendleri ve kullanım verilerini izlemek ve analiz etmek',
    'privacy.section2.use8': 'Teknik sorunları tespit etmek, önlemek ve çözmek',
    'privacy.section2.use9': 'Güvenliği sağlamak ve dolandırıcılığı önlemek',
    'privacy.section3.title': '3. Bilgilerinizi Nasıl Paylaşıyoruz',
    'privacy.section3.intro': 'Bilgilerinizi aşağıdaki durumlarda paylaşabiliriz:',
    'privacy.section3.consentTitle': 'Onayınızla:',
    'privacy.section3.consent1': 'Açık onay verdiğinizde',
    'privacy.section3.consent2': 'İçeriğinizi herkese açık olarak paylaştığınızda',
    'privacy.section3.otherUsersTitle': 'Diğer Kullanıcılarla:',
    'privacy.section3.otherUsers1': 'Herkese açık profil bilgileri ve gönderiler',
    'privacy.section3.otherUsers2': 'Diğer kullanıcılara gönderilen mesajlar',
    'privacy.section3.otherUsers3': 'Kamuya açık içerik üzerindeki yorumlar ve etkileşimler',
    'privacy.section3.serviceProvidersTitle': 'Hizmet Sağlayıcılarla:',
    'privacy.section3.serviceProviders1': 'Bulut depolama ve barındırma hizmetleri',
    'privacy.section3.serviceProviders2': 'Analitik ve performans izleme araçları',
    'privacy.section3.serviceProviders3': 'Müşteri destek ve iletişim hizmetleri',
    'privacy.section3.serviceProviders4': 'Ödeme işleme (varsa)',
    'privacy.section3.legalTitle': 'Yasal Gereklilikler:',
    'privacy.section3.legal1': 'Yasal yükümlülüklere uymak',
    'privacy.section3.legal2': 'Haklarımızı ve mülkiyetimizi korumak',
    'privacy.section3.legal3': 'Dolandırıcılığı veya suistimali önlemek',
    'privacy.section3.legal4': 'Acil durum veya güvenlik gerekçesiyle',
    'privacy.section4.title': '4. Veri Güvenliği',
    'privacy.section4.intro': 'Bilgilerinizi korumak için uygun teknik ve organizasyonel önlemler uygularız:',
    'privacy.section4.security1': 'Veri aktarımı ve saklamada şifreleme',
    'privacy.section4.security2': 'Düzenli güvenlik değerlendirmeleri ve güncellemeler',
    'privacy.section4.security3': 'Erişim kontrolleri ve kimlik doğrulama',
    'privacy.section4.security4': 'Güvenli veri merkezleri ve altyapı',
    'privacy.section4.security5': 'Veri koruma konusunda personel eğitimi',
    'privacy.section4.warning': 'Ancak, internet üzerinden iletim veya elektronik depolama yöntemleri %100 güvenli değildir. Bilgilerinizi korumaya özen göstersek de, mutlak güvenlik garanti edilemez.',
    'privacy.section5.title': '5. Haklarınız ve Seçenekleriniz',
    'privacy.section5.intro': 'Kişisel verilerinizle ilgili belirli haklara sahipsiniz:',
    'privacy.section5.rights1': 'Erişim: Kişisel verilerinizin bir kopyasını talep etme',
    'privacy.section5.rights2': 'Düzeltme: Hatalı bilgilerin düzeltilmesini isteme',
    'privacy.section5.rights3': 'Silme: Kişisel verilerinizin silinmesini talep etme',
    'privacy.section5.rights4': 'Taşınabilirlik: Verilerinizi makine tarafından okunabilir bir formatta talep etme',
    'privacy.section5.rights5': 'Kısıtlama: İşleme faaliyetlerini sınırlama',
    'privacy.section5.rights6': 'İtiraz: Belirli işlemlere itiraz etme',
    'privacy.section5.requestData': 'Verilerinizi Talep Etme',
    'privacy.section6.title': '6. Veri Saklama',
    'privacy.section6.content': 'Bilgilerinizi, Hizmetimizi sağlamak ve bu Gizlilik Politikasında belirtilen amaçları yerine getirmek için gerekli olduğu sürece saklarız. Yasal veya düzenleyici gereklilik olmadıkça, artık gerekli olmadığında bilgilerinizi siler veya anonimleştiririz.',
    'privacy.section7.title': '7. Çocukların Gizliliği',
    'privacy.section7.content': 'Hizmetimiz 13 yaş altındaki çocuklara yönelik değildir. 13 yaş altındaki çocuklardan bilerek bilgi toplamıyoruz. Ebeveyn veya vasiyseniz ve çocuğunuzun bize bilgi verdiğini düşünüyorsanız, lütfen bizimle iletişime geçin.',
    'privacy.section8.title': '8. Uluslararası Veri Aktarımları',
    'privacy.section8.content': 'Bilgileriniz, bulunduğunuz ülke dışındaki ülkelere aktarılabilir ve işlenebilir. Bu tür aktarımların geçerli veri koruma yasalarına uygun olmasını ve uygun güvenlik önlemleriyle korunmasını sağlarız.',
    'privacy.section9.title': '9. Üçüncü Taraf Hizmetleri',
    'privacy.section9.intro': 'Hizmetimiz üçüncü taraf web sitelerine veya hizmetlerine bağlantılar içerebilir. Bu üçüncü tarafların gizlilik uygulamalarından sorumlu değiliz. Bilgi vermeden önce ilgili gizlilik politikalarını okumanızı tavsiye ederiz.',
    'privacy.section9.integratedServicesTitle': 'Entegre Hizmetler:',
    'privacy.section9.integratedServices1': 'Spotify (müzik önerileri için)',
    'privacy.section9.integratedServices2': 'Goodreads (kitap önerileri için)',
    'privacy.section9.integratedServices3': 'Letterboxd (film önerileri için)',
    'privacy.section9.integratedServices4': 'Apple Music (müzik entegrasyonu için)',
    'privacy.section10.title': '10. Bu Gizlilik Politikasındaki Değişiklikler',
    'privacy.section10.content': 'Zaman zaman bu Gizlilik Politikasını güncelleyebiliriz. Değişiklikler, bu sayfada yeni politikanın yayınlanması ve "Son Güncelleme" tarihinin yenilenmesi ile duyurulur.',
    'privacy.section11.title': '11. Kaliforniya Gizlilik Hakları',
    'privacy.section11.intro': 'Eğer Kaliforniya sakiniyseniz, California Consumer Privacy Act (CCPA) kapsamında ek haklara sahipsiniz:',
    'privacy.section11.rights1': 'Toplanan kişisel bilgileri bilme hakkı',
    'privacy.section11.rights2': 'Kişisel bilgilerin silinmesini talep etme hakkı',
    'privacy.section11.rights3': 'Kişisel bilgilerin satışına itiraz etme hakkı',
    'privacy.section11.rights4': 'Gizlilik haklarını kullanma nedeniyle ayrımcılığa uğramama hakkı',
    'privacy.section12.title': '12. Avrupa Birliği Gizlilik Hakları',
    'privacy.section12.intro': 'Eğer Avrupa Ekonomik Alanı\'nda (EEA) ikamet ediyorsanız, GDPR kapsamında şu haklara sahipsiniz:',
    'privacy.section12.rights1': 'Kişisel verilere erişim hakkı',
    'privacy.section12.rights2': 'Yanlış verilerin düzeltilmesi hakkı',
    'privacy.section12.rights3': 'Silme hakkı ("unutulma hakkı")',
    'privacy.section12.rights4': 'İşlemenin kısıtlanması hakkı',
    'privacy.section12.rights5': 'Veri taşınabilirliği hakkı',
    'privacy.section12.rights6': 'İşlemeye itiraz hakkı',
    'privacy.contactUsTitle': 'İletişim',
    'privacy.contactUsIntro': 'Sorularınız için bizimle iletişime geçebilirsiniz:',
    'privacy.contactUsEmail': 'E-posta: shelfieplatform@gmail.com',
    'privacy.contactUsWebsite': 'Web Sitesi: https://shelfieplatform.com',
    'privacy.contactPrivacyTeam': 'Privacy Team ile İletişim Kurun',
    
    // Help Center
    'helpCenter.title': 'Destek Merkezi',
    'helpCenter.back': 'Geri',
    'helpCenter.hero.title': 'Size nasıl yardımcı olabiliriz?',
    'helpCenter.hero.subtitle': 'Cevapları bulun, destek alın ve Shelfie\'den en iyi şekilde yararlanmayı öğrenin',
    'helpCenter.search.placeholder': 'Destek makalelerinde ara...',
    'helpCenter.categories.title': 'Kategoriye Göre Göz At',
    'helpCenter.categories.viewAll': 'Tüm makaleleri gör',
    'helpCenter.categories.gettingStarted.title': 'Başlangıç',
    'helpCenter.categories.gettingStarted.description': 'Shelfie kullanmanın temellerini öğrenin',
    'helpCenter.categories.accountProfile.title': 'Hesap ve Profil',
    'helpCenter.categories.accountProfile.description': 'Hesabınızı ve profil ayarlarınızı yönetin',
    'helpCenter.categories.addingFavorites.title': 'Favori Ekleme',
    'helpCenter.categories.addingFavorites.description': 'Favori içeriklerinizi ekleyin ve düzenleyin',
    'helpCenter.categories.privacySecurity.title': 'Gizlilik ve Güvenlik',
    'helpCenter.categories.privacySecurity.description': 'Gizliliğinizi koruyun ve hesabınızı güvence altına alın',
    'helpCenter.categories.troubleshooting.title': 'Sorun Giderme',
    'helpCenter.categories.troubleshooting.description': 'Yaygın sorunları ve problemleri çözün',
    'helpCenter.categories.contactSupport.title': 'Destek ile İletişim',
    'helpCenter.categories.contactSupport.description': 'Destek ekibimizden doğrudan yardım alın',
    'helpCenter.popular.title': 'Popüler Makaleler',
    'helpCenter.popular.welcome.title': 'Shelfie\'ye Hoş Geldiniz',
    'helpCenter.popular.welcome.description': 'Platformdaki ilk adımlarınız',
    'helpCenter.popular.setupProfile.title': 'Profilinizi ayarlama',
    'helpCenter.popular.setupProfile.description': 'İlgi alanlarınızı yansıtan etkileyici bir profil oluşturun',
    'helpCenter.popular.addBooks.title': 'Favorilerinize kitap ekleme',
    'helpCenter.popular.addBooks.description': 'Dijital rafınızı kitaplarla oluşturmaya başlayın',
    'helpCenter.popular.privacySettings.title': 'Gizlilik ayarları rehberi',
    'helpCenter.popular.privacySettings.description': 'İçeriğinizi ve aktivitelerinizi kimlerin görebileceğini kontrol edin',
    'helpCenter.contact.title': 'Hala yardıma mı ihtiyacınız var?',
    'helpCenter.contact.description': 'Destek ekibimiz herhangi bir soru veya sorunla ilgili size yardımcı olmak için burada.',
    'helpCenter.contact.emailSupport': 'E-posta Desteği',
    'helpCenter.contact.contactForm': 'İletişim Formu',
    'helpCenter.backToHelpCenter': 'Destek Merkezine Dön',
    'helpCenter.gettingStarted.welcome.title': 'Shelfie\'ye Hoş Geldiniz: İlk Adımlarınız',
    'helpCenter.gettingStarted.welcome.description': 'Shelfie ile başlayın ve dijital rafınızı oluşturmanın temellerini öğrenin',
    'helpCenter.gettingStarted.creatingAccount.title': 'Hesabınızı Oluşturma',
    'helpCenter.gettingStarted.creatingAccount.description': 'Shelfie hesabınızı nasıl oluşturacağınızı ve doğrulama sürecini öğrenin',
    'helpCenter.gettingStarted.settingUpProfile.title': 'Profilinizi Ayarlama',
    'helpCenter.gettingStarted.settingUpProfile.description': 'İlgi alanlarınızı ve tercihlerinizi yansıtan etkileyici bir profil oluşturun',
    'helpCenter.gettingStarted.dashboard.title': 'Dashboard\'unuzu Anlama',
    'helpCenter.gettingStarted.dashboard.description': 'Dashboard\'unuzda gezinin ve ana özellikleri anlayın',
    'helpCenter.gettingStarted.privacySettings.title': 'Gizlilik Ayarları Genel Bakış',
    'helpCenter.gettingStarted.privacySettings.description': 'İçeriğinizi kimlerin görebileceğini kontrol edin ve gizliliğinizi yönetin',
    'helpCenter.gettingStarted.mobileApp.title': 'Mobil Uygulama İndirme',
    'helpCenter.gettingStarted.mobileApp.description': 'iOS ve Android için Shelfie mobil uygulamasını indirin',
    'helpCenter.gettingStarted.desktopMobile.title': 'Masaüstü vs Mobil Deneyim',
    'helpCenter.gettingStarted.desktopMobile.description': 'Web ve mobil platformlar arasındaki farkları anlayın',
    'helpCenter.gettingStarted.firstFollowers.title': 'İlk Takipçilerinizi Kazanma',
    'helpCenter.gettingStarted.firstFollowers.description': 'Topluluğunuzu oluşturma ve takipçi kazanma ipuçları',
    'helpCenter.gettingStarted.followingUsers.title': 'Diğer Kullanıcıları Takip Etme',
    'helpCenter.gettingStarted.followingUsers.description': 'Benzer ilgi alanlarına sahip kullanıcıları keşfedin ve takip edin',
    'helpCenter.gettingStarted.notifications.title': 'Bildirimleri Anlama',
    'helpCenter.gettingStarted.notifications.description': 'Bildirim tercihlerinizi yönetin ve güncel kalın',
    'helpCenter.gettingStarted.securityTips.title': 'Temel Güvenlik İpuçları',
    'helpCenter.gettingStarted.securityTips.description': 'Hesabınızı korumak için temel güvenlik uygulamaları',
    'helpCenter.gettingStarted.platformTour.title': 'Platform Turu',
    'helpCenter.gettingStarted.platformTour.description': 'Tüm Shelfie özellikleri ve yeteneklerinin rehberli turunu yapın',
    'helpCenter.backToCategory': 'Kategoriye Dön',
    'helpCenter.articles.welcome.title': 'Shelfie\'ye Hoş Geldiniz: İlk Adımlarınız',
    'helpCenter.articles.welcome.subtitle': 'Shelfie ile başlayın ve dijital rafınızı oluşturmanın temellerini öğrenin',
    'helpCenter.articles.welcome.readTime': '5 dk okuma',
    'helpCenter.articles.welcome.lastUpdated': 'Son güncelleme: Aralık 2024',
    'helpCenter.articles.welcome.introduction.title': 'Dijital Rafınıza Hoş Geldiniz',
    'helpCenter.articles.welcome.introduction.content': 'Shelfie, favori kitaplarınızı, filmlerinizi, müziklerinizi ve dizilerinizi paylaşmak ve keşfetmek için özel olarak tasarlanmış bir sosyal medya platformudur. Kişisel güncellemelere odaklanan geleneksel sosyal medyadan farklı olarak, Shelfie içerik keşfi ve favorilerinizin "dijital rafını" oluşturmaya odaklanır.',
    'helpCenter.articles.welcome.introduction.highlight': 'Shelfie\'yi farklı kılan nedir?',
    'helpCenter.articles.welcome.introduction.highlightContent': 'Shelfie, kişisel güncellemeler yerine içerik küratörlüğüne odaklanır ve sosyal ağınız aracılığıyla yeni kitaplar, filmler ve müzikler keşfetmenize yardımcı olur.',
    'helpCenter.articles.welcome.features.title': 'Temel Özellikler',
    'helpCenter.articles.welcome.features.digitalShelf.title': 'Dijital Raf',
    'helpCenter.articles.welcome.features.digitalShelf.description': 'Favori kitaplarınızı, filmlerinizi, müziklerinizi ve dizilerinizi tek bir yerde toplayın ve düzenleyin.',
    'helpCenter.articles.welcome.features.socialDiscovery.title': 'Sosyal Keşif',
    'helpCenter.articles.welcome.features.socialDiscovery.description': 'Yeni içerikler keşfetmek için diğer kullanıcıları takip edin ve favorilerinizi topluluğunuzla paylaşın.',
    'helpCenter.articles.welcome.features.community.title': 'Topluluk',
    'helpCenter.articles.welcome.features.community.description': 'Kitaplar, filmler ve müzik konusunda benzer ilgi alanlarına sahip kullanıcılarla bağlantı kurun.',
    'helpCenter.articles.welcome.features.recommendations.title': 'Akıllı Öneriler',
    'helpCenter.articles.welcome.features.recommendations.description': 'Tercihlerinize ve sosyal bağlantılarınıza dayalı kişiselleştirilmiş içerik önerileri alın.',
    'helpCenter.articles.welcome.steps.title': 'Başlangıç Kontrol Listesi',
    'helpCenter.articles.welcome.steps.createAccount': 'Hesabınızı oluşturun ve bir kullanıcı adı seçin',
    'helpCenter.articles.welcome.steps.setupProfile': 'Profilinizi biyografi ve ilgi alanlarıyla ayarlayın',
    'helpCenter.articles.welcome.steps.addFavorites': 'Favori kitaplarınızı, filmlerinizi ve müziklerinizi eklemeye başlayın',
    'helpCenter.articles.welcome.steps.followUsers': 'Benzer ilgi alanlarına sahip diğer kullanıcıları takip edin',
    'helpCenter.articles.welcome.steps.exploreContent': 'Öneriler aracılığıyla yeni içerikleri keşfedin',
    'helpCenter.articles.welcome.tips.title': 'Başarı İpuçları',
    'helpCenter.articles.welcome.tips.tip1.title': 'Profilinizi Tamamlayın',
    'helpCenter.articles.welcome.tips.tip1.content': 'Biyografi ve ilgi alanlarıyla dolu bir profil, diğerlerinin sizi keşfetmesine yardımcı olur ve içerik önerilerinizi geliştirir.',
    'helpCenter.articles.welcome.tips.tip2.title': 'Toplulukta Aktif Olun',
    'helpCenter.articles.welcome.tips.tip2.content': 'Bağlantılar kurmak ve yeni favoriler keşfetmek için diğer kullanıcıların içeriklerini beğenin, yorum yapın ve paylaşın.',
    'helpCenter.articles.welcome.tips.tip3.title': 'Listeler ve Koleksiyonlar Kullanın',
    'helpCenter.articles.welcome.tips.tip3.content': 'Favorilerinizi temalı listelere (örn. "Yaz Okumaları", "Korku Filmleri") düzenleyerek diğerleriyle paylaşın.',
    'helpCenter.articles.welcome.related.title': 'İlgili Makaleler',
    'helpCenter.articles.welcome.related.creatingAccount': 'Hesabınızı Oluşturma',
    'helpCenter.articles.welcome.related.settingUpProfile': 'Profilinizi Ayarlama',
    'helpCenter.articles.welcome.related.addingBooks': 'Favorilerinize Kitap Ekleme',
    'helpCenter.articles.welcome.nextArticle': 'Sonraki: Hesabınızı Oluşturma',
    
    // Account & Profile Category
    'helpCenter.accountProfile.changeUsername.title': 'Kullanıcı Adınızı Değiştirme',
    'helpCenter.accountProfile.changeUsername.description': 'Kullanıcı adınızı nasıl güncelleyeceğinizi ve dikkat edilecekleri öğrenin',
    'helpCenter.accountProfile.updateProfile.title': 'Profil Bilgilerinizi Güncelleme',
    'helpCenter.accountProfile.updateProfile.description': 'Profil bilgilerinizi güncel ve doğru tutun',
    'helpCenter.accountProfile.profilePictures.title': 'Profil Fotoğrafları Ekleme',
    'helpCenter.accountProfile.profilePictures.description': 'Profil fotoğrafınızı yükleyin ve yönetin',
    'helpCenter.accountProfile.settingBio.title': 'Biyografinizi Ayarlama',
    'helpCenter.accountProfile.settingBio.description': 'Sizi temsil eden etkileyici bir biyografi yazın',
    'helpCenter.accountProfile.connectedAccounts.title': 'Bağlı Hesapları Yönetme',
    'helpCenter.accountProfile.connectedAccounts.description': 'Sosyal medya hesaplarınızı bağlayın ve yönetin',
    'helpCenter.accountProfile.securitySettings.title': 'Hesap Güvenlik Ayarları',
    'helpCenter.accountProfile.securitySettings.description': 'Hesap güvenlik tercihlerinizi yapılandırın',
    'helpCenter.accountProfile.twoFactorAuth.title': 'İki Faktörlü Kimlik Doğrulama Kurulumu',
    'helpCenter.accountProfile.twoFactorAuth.description': 'Gelişmiş hesap güvenliği için 2FA\'yı etkinleştirin',
    'helpCenter.accountProfile.passwordManagement.title': 'Şifre Yönetimi',
    'helpCenter.accountProfile.passwordManagement.description': 'Hesap şifrenizi değiştirin ve güvence altına alın',
    'helpCenter.accountProfile.accountDeactivation.title': 'Hesap Devre Dışı Bırakma',
    'helpCenter.accountProfile.accountDeactivation.description': 'Hesabınızı geçici veya kalıcı olarak devre dışı bırakın',
    'helpCenter.accountProfile.dataExport.title': 'Veri Dışa Aktarma',
    'helpCenter.accountProfile.dataExport.description': 'Hesap verilerinizi ve içeriğinizi indirin',
    'helpCenter.accountProfile.accountRecovery.title': 'Hesap Kurtarma',
    'helpCenter.accountProfile.accountRecovery.description': 'Hesabınıza erişimi kaybettiğinizde hesabınızı kurtarın',
    'helpCenter.accountProfile.profileVisibility.title': 'Profil Görünürlük Ayarları',
    'helpCenter.accountProfile.profileVisibility.description': 'Profilinizi ve içeriğinizi kimlerin görebileceğini kontrol edin',
    
    // Adding Favorites Category
    'helpCenter.addingFavorites.addBooks.title': 'Favorilerinize Kitap Ekleme',
    'helpCenter.addingFavorites.addBooks.description': 'Arama, ISBN veya manuel giriş kullanarak kitapları dijital rafınıza ekleyin',
    'helpCenter.addingFavorites.addMoviesTv.title': 'Film ve Dizi Ekleme',
    'helpCenter.addingFavorites.addMoviesTv.description': 'Film ve dizileri keşfedin ve koleksiyonunuza ekleyin',
    'helpCenter.addingFavorites.addMusic.title': 'Müzik ve Şarkı Ekleme',
    'helpCenter.addingFavorites.addMusic.description': 'Favori müziklerinizi ve şarkılarınızı rafınıza ekleyin',
    'helpCenter.addingFavorites.importLists.title': 'Mevcut Listelerinizi İçe Aktarma',
    'helpCenter.addingFavorites.importLists.description': 'Koleksiyonlarınızı diğer platformlardan içe aktarın',
    'helpCenter.addingFavorites.organizeFavorites.title': 'Favorilerinizi Düzenleme',
    'helpCenter.addingFavorites.organizeFavorites.description': 'Dijital rafınızı düzenli ve erişilebilir tutun',
    'helpCenter.addingFavorites.customLists.title': 'Özel Listeler Oluşturma',
    'helpCenter.addingFavorites.customLists.description': '"Yaz Okumaları" veya "Korku Filmleri" gibi temalı koleksiyonlar oluşturun',
    'helpCenter.addingFavorites.shareFavorites.title': 'Favorilerinizi Paylaşma',
    'helpCenter.addingFavorites.shareFavorites.description': 'Favori içeriklerinizi arkadaşlarınız ve takipçilerinizle paylaşın',
    'helpCenter.addingFavorites.findContent.title': 'Yeni İçerik Bulma',
    'helpCenter.addingFavorites.findContent.description': 'Öneriler aracılığıyla yeni kitaplar, filmler ve müzikler keşfedin',
    'helpCenter.addingFavorites.ratingReviewing.title': 'Değerlendirme ve İnceleme',
    'helpCenter.addingFavorites.ratingReviewing.description': 'Favori içeriklerinizi değerlendirin ve inceleme yazın',
    'helpCenter.addingFavorites.manageCollections.title': 'Koleksiyonlarınızı Yönetme',
    'helpCenter.addingFavorites.manageCollections.description': 'İçerik koleksiyonlarınızı düzenleyin ve yönetin',
    'helpCenter.addingFavorites.bulkImport.title': 'Toplu İçe Aktarma Seçenekleri',
    'helpCenter.addingFavorites.bulkImport.description': 'Büyük içerik listelerini bir seferde içe aktarın',
    'helpCenter.addingFavorites.favoriteCategories.title': 'Favori Kategoriler',
    'helpCenter.addingFavorites.favoriteCategories.description': 'Favorilerinizi kategoriler ve türlere göre düzenleyin',
    
    // Privacy & Security Category
    'helpCenter.privacySecurity.privacySettings.title': 'Gizlilik Ayarlarınızı Anlama',
    'helpCenter.privacySecurity.privacySettings.description': 'Profilinizi ve içeriğinizi kimlerin görebileceğini kontrol edin',
    'helpCenter.privacySecurity.profileVisibility.title': 'Profilinizi Kimler Görebilir',
    'helpCenter.privacySecurity.profileVisibility.description': 'Profil görünürlüğünüzü ve gizliliğinizi yönetin',
    'helpCenter.privacySecurity.blockingReporting.title': 'Kullanıcı Engelleme ve Şikayet',
    'helpCenter.privacySecurity.blockingReporting.description': 'Kullanıcıları engelleyin ve uygunsuz içerikleri şikayet edin',
    'helpCenter.privacySecurity.dataProtection.title': 'Veri Koruması ve GDPR',
    'helpCenter.privacySecurity.dataProtection.description': 'Veri koruması ve haklarınız hakkında bilgi edinin',
    'helpCenter.privacySecurity.securityBestPractices.title': 'Hesap Güvenliği En İyi Uygulamaları',
    'helpCenter.privacySecurity.securityBestPractices.description': 'Hesabınızı korumak için temel güvenlik uygulamaları',
    'helpCenter.privacySecurity.twoFactorAuth.title': 'İki Faktörlü Kimlik Doğrulama',
    'helpCenter.privacySecurity.twoFactorAuth.description': 'Gelişmiş hesap güvenliği için 2FA kurun',
    'helpCenter.privacySecurity.privacyPolicy.title': 'Gizlilik Politikası Genel Bakış',
    'helpCenter.privacySecurity.privacyPolicy.description': 'Gizliliğinizi nasıl koruduğumuzu anlayın',
    'helpCenter.privacySecurity.dataSharing.title': 'Veri Paylaşım Ayarları',
    'helpCenter.privacySecurity.dataSharing.description': 'Verilerinizin nasıl paylaşıldığını ve kullanıldığını kontrol edin',
    'helpCenter.privacySecurity.thirdPartyIntegrations.title': 'Üçüncü Taraf Entegrasyonları',
    'helpCenter.privacySecurity.thirdPartyIntegrations.description': 'Harici hizmetlere bağlantıları yönetin',
    'helpCenter.privacySecurity.securityNotifications.title': 'Güvenlik Bildirimleri',
    'helpCenter.privacySecurity.securityNotifications.description': 'Hesap güvenliği hakkında bilgi alın',
    'helpCenter.privacySecurity.accountRecovery.title': 'Hesap Kurtarma Seçenekleri',
    'helpCenter.privacySecurity.accountRecovery.description': 'Erişimi kaybettiğinizde hesabınızı kurtarın',
    'helpCenter.privacySecurity.dataDeletion.title': 'Veri Silme Talepleri',
    'helpCenter.privacySecurity.dataDeletion.description': 'Kişisel verilerinizin silinmesini talep edin',
    
    // Troubleshooting Category
    'helpCenter.troubleshooting.loginIssues.title': 'Giriş Sorunları',
    'helpCenter.troubleshooting.loginIssues.description': 'Yaygın giriş problemlerini ve hesap erişim sorunlarını çözün',
    'helpCenter.troubleshooting.appNotLoading.title': 'Uygulama Yüklenmiyor',
    'helpCenter.troubleshooting.appNotLoading.description': 'Uygulama yükleme ve performans sorunlarını düzeltin',
    'helpCenter.troubleshooting.uploadProblems.title': 'Yükleme Sorunları',
    'helpCenter.troubleshooting.uploadProblems.description': 'İçerik ve medya yükleme sorunlarını çözün',
    'helpCenter.troubleshooting.searchNotWorking.title': 'Arama Çalışmıyor',
    'helpCenter.troubleshooting.searchNotWorking.description': 'Arama işlevselliğini ve içerik keşfini düzeltin',
    'helpCenter.troubleshooting.notificationIssues.title': 'Bildirim Sorunları',
    'helpCenter.troubleshooting.notificationIssues.description': 'Bildirim ve uyarı problemlerini çözün',
    'helpCenter.troubleshooting.performanceProblems.title': 'Performans Sorunları',
    'helpCenter.troubleshooting.performanceProblems.description': 'Uygulama ve web sitesi performansını iyileştirin',
    'helpCenter.troubleshooting.browserCompatibility.title': 'Tarayıcı Uyumluluğu',
    'helpCenter.troubleshooting.browserCompatibility.description': 'Web tarayıcınızla uyumluluğu sağlayın',
    'helpCenter.troubleshooting.mobileAppIssues.title': 'Mobil Uygulama Sorunları',
    'helpCenter.troubleshooting.mobileAppIssues.description': 'Mobil uygulamadaki problemleri düzeltin',
    'helpCenter.troubleshooting.accountAccess.title': 'Hesap Erişim Sorunları',
    'helpCenter.troubleshooting.accountAccess.description': 'Hesap erişim ve kimlik doğrulama sorunlarını çözün',
    'helpCenter.troubleshooting.dataSync.title': 'Veri Senkronizasyon Sorunları',
    'helpCenter.troubleshooting.dataSync.description': 'Cihazlar arası veri senkronizasyonunu düzeltin',
    'helpCenter.troubleshooting.errorMessages.title': 'Hata Mesajları',
    'helpCenter.troubleshooting.errorMessages.description': 'Yaygın hata mesajlarını anlayın ve çözün',
    'helpCenter.troubleshooting.contactSupport.title': 'Teknik Destek ile İletişim',
    'helpCenter.troubleshooting.contactSupport.description': 'Teknik destek ekibimizden doğrudan yardım alın',
    
    // Contact Support
    'helpCenter.contact.contactOptions.title': 'İletişim Seçenekleri',
    'helpCenter.contact.emailSupport.title': 'E-posta Desteği',
    'helpCenter.contact.emailSupport.description': 'Bize e-posta gönderin, size geri dönelim',
    'helpCenter.contact.emailSupport.button': 'E-posta Gönder',
    'helpCenter.contact.liveChat.title': 'Canlı Sohbet',
    'helpCenter.contact.liveChat.description': 'Destek ekibimizle gerçek zamanlı sohbet edin',
    'helpCenter.contact.liveChat.button': 'Sohbet Başlat',
    'helpCenter.contact.phoneSupport.title': 'Telefon Desteği',
    'helpCenter.contact.phoneSupport.description': 'Acil yardım için bizi arayın',
    'helpCenter.contact.phoneSupport.button': 'Şimdi Ara',
    'helpCenter.contact.contactForm.title': 'İletişim Formu',
    'helpCenter.contact.form.name': 'Ad',
    'helpCenter.contact.form.namePlaceholder': 'Adınız soyadınız',
    'helpCenter.contact.form.email': 'E-posta',
    'helpCenter.contact.form.emailPlaceholder': 'eposta@ornek.com',
    'helpCenter.contact.form.subject': 'Konu',
    'helpCenter.contact.form.subjectPlaceholder': 'Sorununuzun kısa açıklaması',
    'helpCenter.contact.form.message': 'Mesaj',
    'helpCenter.contact.form.messagePlaceholder': 'Lütfen sorununuzu detaylı olarak açıklayın...',
    'helpCenter.contact.form.submit': 'Mesaj Gönder',
    'helpCenter.contact.supportInfo.title': 'Destek Bilgileri',
    'helpCenter.contact.supportHours.title': 'Destek Saatleri',
    'helpCenter.contact.supportHours.content': 'Pazartesi - Cuma: 09:00 - 18:00 EST',
    'helpCenter.contact.responseTimes.title': 'Yanıt Süreleri',
    'helpCenter.contact.responseTimes.content': 'E-posta: 24-48 saat, Canlı Sohbet: Anında',
    'helpCenter.contact.escalationProcess.title': 'Yükseltme Süreci',
    'helpCenter.contact.escalationProcess.content': 'Karmaşık sorunlar üst düzey desteğe yükseltilir',
    'helpCenter.contact.feedbackOptions.title': 'Geri Bildirim ve Topluluk',
    'helpCenter.contact.feedback.title': 'Genel Geri Bildirim',
    'helpCenter.contact.feedback.description': 'Düşüncelerinizi ve önerilerinizi paylaşın',
    'helpCenter.contact.bugReports.title': 'Hata Raporları',
    'helpCenter.contact.bugReports.description': 'Hataları ve teknik sorunları bildirin',
    'helpCenter.contact.featureRequests.title': 'Özellik Talepleri',
    'helpCenter.contact.featureRequests.description': 'Yeni özellikler ve iyileştirmeler önerin',
    'helpCenter.contact.communityForums.title': 'Topluluk Forumları',
    'helpCenter.contact.communityForums.description': 'Diğer Shelfie kullanıcılarıyla bağlantı kurun',
    
    // Terms of Service
    'terms.title': 'Kullanım Şartları',
    'terms.back': 'Geri',
    'terms.welcome': 'Shelfie\'ye Hoş Geldiniz',
    'terms.intro': 'Bu Kullanım Şartları ("Şartlar"), Shelfie Inc. ("biz", "bize", "bizim") tarafından işletilen Shelfie mobil uygulaması ve ilgili hizmetlerin (topluca "Hizmet") kullanımını düzenler.',
    'terms.lastUpdated': 'Son Güncelleme: Aralık 2024',
    'terms.contact': 'İletişim Bilgileri',
    'terms.contactDescription': 'Bu Kullanım Şartları hakkında soruların varsa bizimle iletişime geç:',
    'terms.contactSupport': 'Destek ile İletişime Geç',
    'terms.viewPrivacyPolicy': 'Gizlilik Politikasını Gör →',
    'terms.section1.title': '1. Şartların Kabulü',
    'terms.section1.content1': 'Hizmetimize erişerek veya onu kullanarak bu Şartlara bağlı kalmayı kabul etmiş olursunuz. Şartların herhangi bir bölümünü kabul etmiyorsanız Hizmete erişmemelisiniz.',
    'terms.section1.content2': 'Bu Şartları zaman zaman bildirim yapmaksızın güncelleme ve değiştirme hakkımız saklıdır. Hizmete eklenen her yeni özellik bu Şartlara tabidir.',
    'terms.section2.title': '2. Hizmetin Tanımı',
    'terms.section2.content1': 'Shelfie, kullanıcıların favori kitaplarını, filmlerini, dizilerini, müziklerini ve podcastlerini paylaşmasına ve keşfetmesine olanak tanıyan bir sosyal medya platformudur. Hizmet şunları içerir:',
    'terms.section2.list1': 'Kişisel profiller oluşturma ve yönetme',
    'terms.section2.list2': 'Favori içerikleri toplulukla paylaşma',
    'terms.section2.list3': 'Öneriler aracılığıyla yeni içerikler keşfetme',
    'terms.section2.list4': 'Diğer kullanıcıları takip etme ve bağlantı kurma',
    'terms.section2.list5': 'Kişiselleştirilmiş içerik akışına erişim',
    'terms.section2.list6': 'Topluluk tartışmalarına katılma',
    'terms.section3.title': '3. Kullanıcı Hesapları',
    'terms.section3.content1': 'Hizmetin belirli özelliklerine erişmek için hesap açmanız gerekir. Bununla birlikte:',
    'terms.section3.list1': 'Doğru ve güncel bilgiler vermeyi',
    'terms.section3.list2': 'Hesap bilgilerinizi güncel tutmayı',
    'terms.section3.list3': 'Şifrenizi gizli ve güvenli tutmayı',
    'terms.section3.list4': 'Hesabınız altındaki tüm faaliyetlerden sorumlu olmayı',
    'terms.section3.list5': 'Yetkisiz kullanım durumunda derhal bizi bilgilendirmeyi kabul edersiniz.',
    'terms.section3.content2': 'Hesap açmak için en az 13 yaşında olmalısınız. 18 yaş altı kullanıcıların ebeveyn onayı gereklidir.',
    'terms.section4.title': '4. Kullanıcı İçeriği ve Davranışı',
    'terms.section4.content1': 'Kullanıcı olarak paylaştığınız tüm içerikten siz sorumlusunuz. Aşağıdakileri yapmamayı kabul edersiniz:',
    'terms.section4.list1': 'Yasadışı, zararlı veya başkalarının haklarını ihlal eden içerik paylaşmak',
    'terms.section4.list2': 'Telif hakkıyla korunan materyalleri izinsiz paylaşmak',
    'terms.section4.list3': 'Spam, yanıltıcı veya aldatıcı içerik göndermek',
    'terms.section4.list4': 'Diğer kullanıcılara taciz veya zarar vermek',
    'terms.section4.list5': 'Başkalarını taklit etmek veya sahte hesap oluşturmak',
    'terms.section4.list6': 'İzin olmadan ticari amaçlarla hizmeti kullanmak',
    'terms.section4.content2': 'Bu Şartları ihlal eden içerikleri kaldırma ve hesapları askıya alma hakkımız saklıdır.',
    'terms.section5.title': '5. Gizlilik ve Veri Koruma',
    'terms.section5.content1': 'Gizliliğiniz bizim için önemlidir. Kişisel verilerinizin toplanması ve kullanımı, Gizlilik Politikamızda açıklanmıştır. Hizmeti kullanarak Gizlilik Politikamızı kabul etmiş olursunuz.',
    'terms.section6.title': '6. Fikri Mülkiyet',
    'terms.section6.content1': 'Hizmet ve orijinal içerikleri, özellikleri ve işlevleri Shelfie Inc.\'e aittir ve uluslararası telif hakkı, marka, patent ve diğer fikri mülkiyet yasaları ile korunmaktadır.',
    'terms.section6.content2': 'Kullanıcı olarak oluşturduğunuz içerik size aittir, ancak bu içerikleri Hizmet kapsamında kullanmamız, görüntülememiz ve dağıtmamız için bize lisans vermiş olursunuz.',
    'terms.section7.title': '7. Yasaklı Kullanımlar',
    'terms.section7.content1': 'Hizmeti aşağıdaki amaçlarla kullanamazsınız:',
    'terms.section7.list1': 'Yasadışı faaliyetler veya başkalarını yasadışı eyleme teşvik',
    'terms.section7.list2': 'Ulusal veya uluslararası yasa ve düzenlemeleri ihlal',
    'terms.section7.list3': 'Başkalarının fikri mülkiyet haklarını ihlal',
    'terms.section7.list4': 'Hakaret, taciz, tehdit, ayrımcılık veya kötüye kullanım',
    'terms.section7.list5': 'Yanlış veya yanıltıcı bilgi sağlama',
    'terms.section7.list6': 'Virüs veya zararlı kod yükleme veya iletme',
    'terms.section8.title': '8. Hizmetin Kullanılabilirliği',
    'terms.section8.content1': 'Sürekli hizmet sağlamaya özen göstersek de kesintisiz erişim garantisi veremeyiz. Bakım, teknik arızalar veya diğer nedenlerle hizmeti değiştirme, askıya alma veya sonlandırma hakkımız saklıdır.',
    'terms.section8.content2': 'Hizmeti istediğimiz zaman değiştirme, askıya alma veya sonlandırma hakkımız saklıdır.',
    'terms.section9.title': '9. Sorumluluk Reddi ve Sınırlamalar',
    'terms.section9.content1': 'Hizmet, "OLDUĞU GİBİ" ve "MEVCUT DURUMDA" sunulmaktadır. Açık veya zımni hiçbir garanti vermeyiz.',
    'terms.section9.content2': 'Shelfie Inc., dolaylı, tesadüfi, özel, sonuçsal veya cezai zararlardan sorumlu değildir.',
    'terms.section10.title': '10. Fesih',
    'terms.section10.content1': 'Hesabınızı, bu Şartların ihlali dahil olmak üzere, herhangi bir nedenle ve önceden bildirimde bulunmaksızın askıya alma veya sonlandırma hakkımız vardır.',
    'terms.section10.content2': 'Hesabınızı kapatmak isterseniz Hizmeti kullanmayı bırakabilir veya bize başvurarak silme talebinde bulunabilirsiniz.',
    'terms.section11.title': '11. Geçerli Hukuk',
    'terms.section11.content': 'Bu Şartlar, Kaliforniya Eyaleti (ABD) yasalarına tabi olup, kanunlar ihtilafı hükümleri dikkate alınmaksızın yorumlanır.',
    'terms.section12.title': '12. Şartlardaki Değişiklikler',
    'terms.section12.content1': 'Bu Şartları istediğimiz zaman değiştirme veya güncelleme hakkımız saklıdır. Önemli değişiklikler için en az 30 gün önceden bildirim yapılacaktır.',
    'terms.section12.content2': 'Değişikliklerden sonra Hizmeti kullanmaya devam ederek yeni şartları kabul etmiş sayılırsınız.',
    'terms.loading': 'Kullanım şartları yükleniyor...',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
